### ISSUE TITLE
Drinking sake causes ticking EntityPlayerMP to fail

### ISSUE THREAD

**Issue by InashiKaari** [GrowthcraftCE/Growthcraft-1.12#191]
If i try drinking sake on the server, it automaticly kicks me out, and says, internal server error.
When i get back into my server the sake is still in my hand. This issue does not appear in singleplayer tho.

This what the server console says:

[K[33;1m[18:45:52] [Server thread/WARN] inecraft/NetworkSystem]: Failed to handle packet for /185.233.26.144:51094
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.NullPointerException
        at net.minecraft.util.FoodStats.func_151686_a(SourceFile:32) ~[afp.class:?]
        at growthcraft.core.shared.item.GrowthcraftItemFoodBase.func_77654_b(GrowthcraftItemFoodBase.java:96) ~[GrowthcraftItemFoodBase.class:?]
        at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:222) ~[aip.class:?]
        at net.minecraft.entity.EntityLivingBase.func_71036_o(EntityLivingBase.java:2789) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71036_o(EntityPlayerMP.java:1125) ~[oq.class:?]
        at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:2688) ~[vp.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2097) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
        ... 9 more
[39;0m
[K[18:45:52] [Server thread/INFO] inecraft/NetHandlerPlayServer]: Nexu lost connection: Internal server error

[K[18:45:52] [Server thread/INFO] inecraft/DedicatedServer]: Nexu[39;0m left the game[39;0m[39;0m

**Comment by Alatyami** [comment]
Which version are you running?

**Comment by InashiKaari** [comment]
growthcraft-1.12.2-4.0.4.500
on a standard forge server

**Comment by Alatyami** [comment]
What is your version of Forge? I just tried to duplicate the issue with the following and couldn't trigger it.

Forge: 14.23.5.2768
Growthcraft: 4.0.5.100

**Comment by Avatair** [comment]
It is possible that bug with a server crash when food stats is counted by drinking. It occurs together with some popular coremod it seems as there are some people complaining about it.

**Comment by Alatyami** [comment]
Unable to duplicate, closing it out. Similiar to #41
