### ISSUE TITLE
NullPointer Crash on Test Server

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.12#305]
When placing Thistle into the Kettle the server crashes. Cleared out the configs on the server and the client and it still crashes. 

`[02:47:55] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: 
  Encountered an unexpected exception net.minecraft.util.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.NullPointerException
        at growthcraft.cellar.common.tileentity.device.BrewKettle.canProcess(BrewKettle.java:83) ~[BrewKettle.class:?]
        at growthcraft.core.shared.tileentity.device.DeviceProgressive.update(DeviceProgressive.java:115) ~[DeviceProgressive.class:?]
        at growthcraft.cellar.common.tileentity.device.BrewKettle.update(BrewKettle.java:119) ~[BrewKettle.class:?]
        at growthcraft.cellar.common.tileentity.TileEntityBrewKettle.func_73660_a(TileEntityBrewKettle.java:132) ~[TileEntityBrewKettle.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1835) ~[amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
        ... 4 more`

**Comment by Alatyami** [comment]
Fixed it ... it was due to the config files ... again. 

Resolved the crashing when the configs are bad by putting in a try/catch and added some logging telling users what to do when it happens.
