### ISSUE TITLE
Piping into culture jar causes crash

### ISSUE THREAD

**Issue by alisww** [GrowthcraftCE/Growthcraft-1.12#337]
Piping into a Culture Jar causes a crash.
(Pipes that i've tried:  TE's fluiducts, Mekanism's mechanical pipes, IE's fluid pipes)
Versions: 4.1.3.100 and 4.1.3.200

`Caused by: java.lang.IndexOutOfBoundsException: readerIndex(32) + length(1869966951) exceeds writerIndex(256): UnpooledHeapByteBuf(ridx: 32, widx: 256, cap: 256/256)
    at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1396)
    at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1383)
    at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:850)
    at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:858)
    at growthcraft.core.shared.io.stream.StreamUtils.readStringASCII(StreamUtils.java:31)
    at growthcraft.core.shared.io.stream.StreamUtils.readFluidTank(StreamUtils.java:60)
    at growthcraft.core.shared.fluids.FluidTanks.readFromStream(FluidTanks.java:166)
    at growthcraft.core.shared.tileentity.GrowthcraftTileDeviceBase.readFromStream_FluidTanks(GrowthcraftTileDeviceBase.java:260)
    ... 24 more`

**Comment by Alatyami** [comment]
Just tested with IE pipes an now crash ...

**Comment by Alatyami** [comment]
With the 4.2.0 version, I cannot duplicate the array out of bounds.
