### ISSUE TITLE
Issue: Crash with grapes.

### ISSUE THREAD

**Issue by 1SnowBall1** [GrowthcraftCE/Growthcraft-1.12#352]
When I plant the grapes it suddenly crashes, there is not an algorythm it just suddenly happens or sometimes it doesn't but when i think I'm fine, it crashes and it is painful, I wanted to play arround with grapes :(

**Comment by Alatyami** [comment]
Please post your log and we can take a look.

**Comment by Alatyami** [comment]
Also, which version are you running?

**Comment by 1SnowBall1** [comment]
Hello, I am running the 1.12.2 version, exactly this one growthcraft-1.12.2-4.2.1, and the forge version is 1.12.2-forge-14.23.5.2854.
The log is the crash report, am I right?

**Comment by Alatyami** [comment]
Thanks, yes the crash report will tell us the issue.

**Comment by 1SnowBall1** [comment]
[crash-2020-12-13_15.56.47-server.txt](https://github.com/GrowthcraftCE/Growthcraft-1.12/files/5684770/crash-2020-12-13_15.56.47-server.txt)

There it is.
I don't know why it says 'server', I recreated the crash in a singleplayer world. 
Thanks.

**Comment by Alatyami** [comment]
We'll take a look. Single player actually runs a "server" locally.

**Comment by Alatyami** [comment]
I have been able to duplicate the issue, thank you for reporting it. We'll have an update pushed out soon.

**Comment by xJon** [comment]
Is there any ETA for `4.2.2`? Thank you!

**Comment by Alatyami** [comment]
Today 🗡️

**Comment by darthvader45** [comment]
YES!

**Comment by clienthax** [comment]
Same problem with hops
```
java.lang.IllegalAccessError: tried to access method net.minecraft.block.BlockCrops.func_180672_a(Lnet/minecraft/block/Block;Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;)F from class growthcraft.hops.common.block.BlockHops
    at growthcraft.hops.common.block.BlockHops.getGrowthRate(BlockHops.java:254)
    at growthcraft.hops.common.block.BlockHops.getGrowthRateLoop(BlockHops.java:200)
    at growthcraft.hops.common.block.BlockHops.grow(BlockHops.java:236)
    at growthcraft.hops.common.block.BlockHops.updateTick(BlockHops.java:162)
    at net.minecraft.block.Block.randomTick(Block.java:508)
    at org.spongepowered.common.event.tracking.TrackingUtil.randomTickBlock(TrackingUtil.java:310)
    at net.minecraft.world.WorldServer.updateBlocks(WorldServer.java:3815)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:225)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by Alatyami** [comment]
I'll double check and test hops before releasing. Thanks for the follow-up.

**Comment by SirOMGitsYOU** [comment]
> I'll double check and test hops before releasing. Thanks for the follow-up.

Still having this issue on the latest version of GC:CE

[crash-2021-02-25_17.47.36-server.txt](https://github.com/GrowthcraftCE/Growthcraft-1.12/files/6058224/crash-2021-02-25_17.47.36-server.txt)
