### ISSUE TITLE
Grapes crash out server on random growth tick

### ISSUE THREAD

**Issue by mate7151** [GrowthcraftCE/Growthcraft-1.12#356]
Using version 4.2.1 with forge-14.23.5.2854.

Encountered the following server crash shortly after planting some grapes, doesn't look like it interacted with any other mods.
`Description: Exception ticking world

java.lang.IllegalAccessError: tried to access method net.minecraft.block.BlockCrops.func_180672_a(Lnet/minecraft/block/Block;Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;)F from class growthcraft.grapes.common.blocks.BlockGrapeVineBase
    at growthcraft.grapes.common.blocks.BlockGrapeVineBase.getGrowthRate(BlockGrapeVineBase.java:82)
    at growthcraft.grapes.common.blocks.BlockGrapeVineBase.updateTick(BlockGrapeVineBase.java:160)
    at net.minecraft.block.Block.randomTick(Block.java:508)
    at net.minecraft.world.WorldServer.updateBlocks(WorldServer.java:476)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:225)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
`

**Comment by mate7151** [comment]
Sorry, completely missed that this was a known issue -- didn't realize there was a separate branch dedicated to it.
