### ISSUE TITLE
[Crash] Issue between the Culture Jar/Cheese vat and OpenJ9 (will never be fixed)

### ISSUE THREAD

**Issue by gatoborrachon** [GrowthcraftCE/Growthcraft-1.12#363]
Sorry, its me again, In short, the culture jar has 2 related issues:
1.- it causes [soft-crashes](https://pastebin.com/G04uQsVd) when you add the skim milk before putting a fire source near.

2.- and if you start heating the Cuture Jar before adding the milk it will freeze the game so badly along with the soft crashes (after putting the milk) and a strange render issue where the milk inside the culture jar renders from the jar to the sky, you can stop this freeze by breaking the Culture Jar. 

(EDIT: also the production of Starter Culture seems to not work, i think its the same issue as https://github.com/GrowthcraftCE/Growthcraft-1.12/issues/346 but here we can see a different (and crashier) behavior), 

Video about the Culture Jar: https://streamable.com/qrzsyx

also, when you place the cheese vat it crash the game without crash report, anyways here's the [latest.log](https://github.com/GrowthcraftCE/Growthcraft-1.12/files/5898350/latest.log)

i can confirm that these issues happen with only this mod, so i think you don't know how to fix them right?

**Comment by Alatyami** [comment]
Awesome video ... that helps a ton. Can you post your config/growthcraft/cellar/culturing.json file? Seems that there's been some customization to it as the default tank size for the jar is one bucket.

**Comment by gatoborrachon** [comment]
i never changed something inside the config folder but anyways here it is:
https://pastebin.com/jqgzmApB

also, i would like to add something:
1.- i found a way to produce Culture Starter:
do what i say in the point 2, as soon as you are inside the gui, click the big red X to delete the fluid, it will stop the freezing, now add again the Skim Milk but never right-click the Culture Jar again, and it will produce Culture Starter, you can see it with Waila or by breaking the Culture Jar after some minutes. 

2.- The issue related to the Cheese Vat causes a deadly freeze when you have a lot of mods, but when you are alone with Growhtcraft it simply freezes the game for a couple of seconds, i wish this info helps you to find the solution, i really like the way to produce Butter and Cheese and it matches perfectly with Heat&Climate.
EDIT: the freezes also happen when you add an ingredient (and they are also deadly freezes when you have a lot of mods)
(last part of Latest.log where the deadly freeze happen: https://pastebin.com/xiSb6vTq (i think it is related to NEI right?))
EDIT 2: It seems to be related to NEI, without it i get his soft crash: https://pastebin.com/DFLBLffK (pretty similar to the Culture Jar's one)

3.- Things does not render in Cheese Vat 
EDIT: when i entered to the same world with all my mods, the cheese vat was rendering its ingredients
![2021-02-08_23 48 36](https://user-images.githubusercontent.com/61126174/107322387-005b6780-6a6a-11eb-8542-7756bc5c1b9b.png)


Video about the 3 things above: https://streamable.com/v2l8tt

**Comment by Alatyami** [comment]
Delete your growthcraft config folder. You are missing most of the culture jar config it needs to rebuild. Likely missing newer configs for the cheese vat as well. I've tested it with my personal modpack which has 119 mods, you shouldn't see lag due to the vat.

**Comment by gatoborrachon** [comment]
> You are missing most of the culture jar config it needs to rebuild.
> I've tested it with my personal modpack which has 119 mods, you shouldn't see lag due to the vat.

1.- really? mmm, can you give a copy of your modpack? (with config folder, or at least this folder), i never changed anything in the config nor have idea why that happens.

2.- also, you would like to try my [personal modpack](https://www.mediafire.com/file/vnv0vbwwq993kqd/mods+completos+1.12.rar/file) to check this by yourself? 

2.1.- i think that NEI is they guilty mod when we talk about the deadly freezes (it doesn't generates a crash but it is registered in Latest.log) (also is there nothing you can do or tell me to do to fix it? or i must remove NEI to play GrowthCraft?)
-tell me if i need to make an issue in NEI's Github but idk if i will recieve a fix by its author, that mod does not updates since 2019

2.2.- but without NEI it only causes a freeze of around ~~45 seconds~~ along with a soft crash, as i said on my comment above yours.
EDIT: only without NEI it causes a freeze of like 20 minutes, i removed another 2 mods and the freeze was around 45 seconds

**Comment by gatoborrachon** [comment]
and i would like to add that another modder told me that we are having issues with networking on this issue:

> Caused by: java.lang.IndexOutOfBoundsException: readerIndex(32) + length(256) exceeds writerIndex(256): UnpooledHeapByteBuf(ridx: 32, widx: 256, cap: 256/256)
>     at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1396)
>     at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1383)
>     at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:850)
>     at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:858)
>     at growthcraft.core.shared.io.stream.StreamUtils.readStringASCII(StreamUtils.java:31)
> 
> Looks like they're having networking issues. Anyway, I'm not familiar with their codebase, so it's probably best to leave it up to them.

**Comment by Alatyami** [comment]
> > You are missing most of the culture jar config it needs to rebuild.
> > I've tested it with my personal modpack which has 119 mods, you shouldn't see lag due to the vat.
> 
> 1.- really? mmm, can you give a copy of your modpack? (with config folder, or at least this folder), i never changed anything in the config nor have idea why that happens.
> 
> 2.- also, you would like to try my [personal modpack](https://www.mediafire.com/file/vnv0vbwwq993kqd/mods+completos+1.12.rar/file) to check this by yourself?
> 
> 2.1.- i think that NEI is they guilty mod when we talk about the deadly freezes (it doesn't generates a crash but it is registered in Latest.log) (also is there nothing you can do or tell me to do to fix it? or i must remove NEI to play GrowthCraft?)
> -tell me if i need to make an issue in NEI's Github but idk if i will recieve a fix by its author, that mod does not updates since 2019
> 
> 2.2.- but without NEI it only causes a freeze of around ~45 seconds~ along with a soft crash, as i said on my comment above yours.
> EDIT: only without NEI it causes a freeze of like 20 minutes, i removed another 2 mods and the freeze was around 45 seconds

I only use the default config for Growthcraft. 

I wouldn't expect any issues with NEI as all of our blocks and items are standard and we do not register our custom devices with NEI. 

I'll test it with your pack, might take a few days to get to it though.

**Comment by Alatyami** [comment]
RenderIndex issue is caused by the config for culturing.json not being correct. The tank level appears to be more than the 4000 mb and the renderer for the tank is confused.

**Comment by gatoborrachon** [comment]
(sorry for the delay, i had a virtual class)
mmmmmm, well, i'm certainly without ideas, maybe its the launcher? maybe its because i'm using OpenJ9?

i will try the last one, wish it works, but idk then what to do, i already posted issues on their github related to other mods, but in these cases it was obviously that it was because of OpenJ9, 
Examples:
https://github.com/eclipse/openj9/issues/11433
https://github.com/eclipse/openj9/issues/11271

EDIT: It seems to be the cause, you may know what could be wrong? with the other issues we knew what was happening, also, the render issues are gone (i'm fucked right? i mean, is there nothing you can do to fix this from your side? i have no idea if someone in OpenJ9 know what is happening here, these issues of FutureTaks are so generic)

**Comment by gatoborrachon** [comment]
well, i mainly use OpenJ9 because it helps my potato to run mods smoothly, try it and see if it will worth the effort to fix whatever is going wrong here, these are the arguments i use: 
-Xms256M -Xmx4596M -XX:+DisableExplicitGC -XX:+AlwaysPreTouch

**Comment by gatoborrachon** [comment]
well, it happened what i was worrying, anyways many thanks for continuing my case until the end.
